worker_config:
  exec_type: it
  ports: "443:443"
  network: ai_network
  container_name: worker
  image_name: worker-image

aphrodite_config:
  exec_type: it
  ports: "2242:7860"
  network: ai_network
  container_name: aphrodite-engine
  gpus: "all"
  shm-size: "8g"
  env:
    - MODEL_NAME=TheBloke/Mistral-7B-v0.1-GPTQ #See list of models supported, take note of required VRAM
    - KOBOLD_API=true
    - GPU_MEMORY_UTILIZATION=0.8 #If you are running out of memory, consider decreasing this value
  image_name: alpindale/aphrodite-engine
